version: "3.9"  # optional since v1.27.0
services:
  web_api:
    image: fsa.so.webapi
    build:
      context: .
      dockerfile: WebApiSO/Dockerfile # the Dockerfile is stored in the FSA.Map.WebApi project
    environment:
    - ASPNETCORE_ENVIRONMENT=Development
    - ASPNETCORE_URLS=https://+:443;http://+:80
    - ASPNETCORE_Kestrel__Certificates__Default__Password=zaqWE*123
    - ASPNETCORE_Kestrel__Certificates__Default__Path=/https/MapsApiSSLCert.pfx
    ports:
      - "443:443"
      #- "5000:80"
    depends_on:
      - mssqlserver
    volumes:
      - ./Dockerizing_api/https:/https:ro
    container_name: SO-API
    networks:
        BiomesysAsistenciaNetwork:
            ipv4_address: 172.26.0.113
  mssqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      - ACCEPT_EULA=Y 
      - SA_PASSWORD=zaqWE*123
      - MSSQL_AGENT_ENABLED=True
      - MSSQL_PID=Developer
    ports: # not actually needed, because the two services are on the same network
      - "1433:1433"
    volumes:
      - ./Dockerizing_api/mssql-server-data:/var/opt/mssql/data
      - ./Dockerizing_api/mssql-server-logs:/var/opt/mssql/log
    container_name: ms-sqlserver2022-API
    restart: always
    networks:
        BiomesysAsistenciaNetwork:
            ipv4_address: 172.26.0.114
networks:
  BiomesysAsistenciaNetwork:
    ipam:
      config:
        - subnet: 172.26.0.0/24